#!/bin/bash
# number of threads:
for t in 1 2 4
do
	echo NUMT = $t
	# number of nodes
	for s in 100 1000 2000 4000 5000 10000
	do
		echo NUMNODES = $s
		g++ -DNUMNODES=$s -DNUMTHREADS=$t HeightEval.cpp -o HeightEval -lm -fopenmp
		./HeightEval
	done
done
