#!/bin/bash
# number of threads:
for t in 1 4
do
	echo NUMT = $t
	# number of subdivisions
	for s in 1024 4096 8192 16384 32768 65536 131072
	do
		echo ARRAYSIZE = $s
		g++ -DARRAYSIZE=$s -DNUMT=$t project0.cpp -o project0 -lm -fopenmp
		./project0
	done
done
