#!/bin/bash
gcc -o otp_enc_d otp_enc_d.c otp_functions.c otp_functions.h
gcc -o otp_enc otp_enc.c otp_functions.c otp_functions.h
gcc -o otp_dec_d otp_dec_d.c otp_functions.c otp_functions.h
gcc -o otp_dec otp_dec.c otp_functions.c otp_functions.h
gcc -o keygen keygen.c